# Generated by Django 4.2.3 on 2023-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vet',
            field=models.BooleanField(default=False),
        ),
    ]
