# Generated by Django 4.2.3 on 2023-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_savedanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanimal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
