# Generated by Django 4.2.3 on 2023-07-27 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0006_alter_savedanimal_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedanimal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedanimal',
            name='review_hour',
            field=models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedanimal',
            name='review_type',
            field=models.CharField(choices=[('Primary examination', 'Primary examination'), ('Castration', 'Castration'), ('Vaccination', 'Vaccination'), ('Deworming', 'Deworming')], default='Primary examination', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='savedanimal',
            unique_together={('user', 'animal', 'review_hour')},
        ),
    ]
