# Generated by Django 4.2.3 on 2023-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_alter_savedanimal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanimal',
            name='review_hour',
            field=models.CharField(choices=[(9, 9), (10, 10), (11, 11), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], max_length=10),
        ),
    ]
