# Generated by Django 4.2.3 on 2023-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_alter_savedanimal_review_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanimal',
            name='review_hour',
            field=models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)]),
        ),
    ]
