# Generated by Django 4.2.3 on 2023-08-01 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0011_medicalexamination_vet_alter_medicalexamination_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalexamination',
            name='vet',
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
